# Generated by Django 4.1.7 on 2023-03-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=200)),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_de_estreno', models.DateField()),
                ('descripcion', models.TextField()),
                ('generos', models.CharField(max_length=200)),
            ],
        ),
    ]
