# Generated by Django 4.1.7 on 2023-03-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Buscador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='generos',
            field=models.CharField(choices=[('Pelicula', 'pl'), ('Serie', 'sr'), ('Novela', 'nv')], max_length=50),
        ),
    ]
