# Generated by Django 4.1.7 on 2023-03-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Buscador', '0002_alter_contenido_generos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='generos',
            field=models.CharField(choices=[('pl', 'Pelicula'), ('sr', 'Serie'), ('nv', 'Novela')], max_length=50),
        ),
    ]
