# Generated by Django 4.1.7 on 2023-03-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Buscador', '0003_alter_contenido_generos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='categoria',
            field=models.CharField(choices=[('pl', 'Pelicula'), ('sr', 'Serie'), ('nv', 'Novela')], max_length=50),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='generos',
            field=models.CharField(max_length=200),
        ),
    ]
