# Generated by Django 4.1.7 on 2023-03-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Buscador', '0004_alter_contenido_categoria_alter_contenido_generos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='categoria',
            field=models.CharField(choices=[('Pelicula', 'Pelicula'), ('Serie', 'Serie'), ('Novela', 'Novela')], max_length=50),
        ),
    ]
